baseURL: "https://giwonbahg.github.io" 
title: Giwon Bahg
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: GiwonBahg_CV.pdf
          weight: 2
        - name: About me
          url: aboutme/
          weight: 3
        - name: Research
          url: research/
          weight: 4
        - name: Publication
          url: publication/
          weight: 5
        - name: Home
          url: /
          weight: 1

params:
    description: "I am a computational cognitive psychologist."
    author: Giwon Bahg
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Giwon Bahg
          subtitle: "(he/him)<br><br>Hello! I am a computational cognitive scientist. I am currently a postdoctoral researcher in the Department of Psychology at Vanderbilt University.<br><br>I study how we learn and apply knowledge of concepts and categories in a dynamic, interactive environment. I am also interested in understanding cognition via modeling brain and behavioral data simultaneously."
          imageUrl: "GiwonBahg_picture0.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Giwon Bahg
          buttons:
            - name: CV
              url: GiwonBahg_CV.pdf
            - name: About Me
              url: aboutme/
            - name: Research
              url: research/
            - name: Publication
              url: publication/
            #- name: Tags
            #  url: tags/

    socialIcons:
        - name: CV
          url: GiwonBahg_CV.pdf
        - name: Email
          url: mailto:giwon.bahg.1@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cCuYSqgAAAAJ&hl
        - name: GitHub
          url: https://github.com/giwonbahg

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Giwon Bahg"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2